### ISSUE TITLE
Bug when manually adding a colored logo in the configuration file.

### ISSUE THREAD

**Issue by MDrzd** [luisadha/alfetch#2]
Bug when manually adding a colored ascii art in the configuration file.

**Comment by luisadha** [comment]
> Bug when manually adding a colored logo in the configuration file.


# **bug** _when manually adding a colored logo in the configuration file_


### Explanation

It may be that my code cannot count Ascii color code bytes or others, it can only count single characters because I have confirmed by testing turning off the color code function and then observing the changes and the results obtained if ascii art characters are inserted if there is no color then the code will be fine.


### Solution

The solution you can use the following command

```sh
alfetch | lolcat
```

or you can try this for not rainbows

```sh
alfetch | lolcrab -c green
```

this worked for me.
